---
- name: Determine whether to connect as root or admin_user
  local_action: shell ssh -o PasswordAuthentication=no root@{{ inventory_hostname }} "echo can_connect"
  failed_when: false
  changed_when: false
  register: root_status

- name: Set remote user for each host
  set_fact:
    ansible_ssh_user: "{{ (root_status.stdout == 'can_connect') | ternary('root', admin_user) }}"
